### PR TITLE
fixed ciphertext concatenation

### PR DESCRIPTION
**Pull request by AhmetMelihSerter**

### CODE REVIEW

**Comment by AhmetMelihSerter** [comment]
When this will be merged?

**Comment by na2axl** [comment]
Hi @dint-dev, this is an important fix since encryption/decryption (with AES/GCM for me) in the new version (2.0.0) is broken... Why it's not merged yet?

**Comment by harryfei** [comment]
Merge this plz.

**Comment by Coronon** [comment]
I just independently rediscovered this bug and came up with the same fix. Why is something this important not merged?!

**Review by terrier989 — APPROVED** [review]

**Comment by terrier989** [comment]
Thanks for the pull request! Apologies for taking this long. I would hope to find new Github repository & Pub package maintainers for this package as I've been busy with other things.

**Comment by Coronon** [comment]
Btw. you only approved the changes, you _did not merge them_. Probably a misclick?

**Comment by AhmetMelihSerter** [comment]
Please merge this. @terrier989

**Comment by terrier989** [comment]
Fixed in 2.0.2, which has been published in pub.dev.

**Pull request closed without merging**
