### PR TITLE
Fix web crypto not working with dart2js

### LINKED ISSUE #28: [WEB] Cannot find native JavaScript type (crypto.CryptoKey) for type check
I got the next error when trying to use code from the example in chrome browser:
Cannot find native JavaScript type (crypto.CryptoKey) for type check
Error: Expected a value of type 'FutureOr<JSObject<crypto.CryptoKey>>?', but got one of type 'CryptoKey'

Code sample, platform web
`import 'dart:convert';

import 'package:cryptography/cryptography.dart';

Future<void> main() async {
  // Choose the cipher
  final cipher = CipherWithAppendedMac(aesCtr, Hmac(sha256));

  // Choose some 256-bit secret key
  final secretKey = SecretKey.randomBytes(16);

  // Choose some unique (non-secret) nonce (max 16 bytes).
  // The same (secretKey, nonce) combination should not be used twice!
  final nonce = Nonce.randomBytes(12);

  // Our message
  final message = utf8.encode('encrypted message');

  // Encrypt
  final encrypted = await cipher.encrypt(
    message,
    secretKey: secretKey,
    nonce: nonce,
  );

  print('Encrypted: $encrypted');

  // Decrypt
  final decrypted = await cipher.decrypt(
    encrypted,
    secretKey: secretKey,
    nonce: nonce,
  );

  print('Decrypted: $decrypted');
}`

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-6.0.pre.91, on Microsoft Windows [Version 10.0.17763.1282], locale uk-UA)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.2)
[√] Android Studio (version 3.6)
[√] Connected device (3 available)

• No issues found!

### PR DESCRIPTION
**Pull request by CDDelta**
Package now works when compiling with dart2js.

Closes #28

### CODE REVIEW

**Comment by CDDelta** [comment]
Sadly, looks like this fix doesn't work when using dart2js, only dartdevc. Anyone have ideas how to fix this?

**Comment by CDDelta** [comment]
I'm using [this](https://github.com/google/webcrypto.dart/blob/master/lib/src/crypto_subtle.dart) as a reference for the bindings and nothing looks wrong

**Comment by CDDelta** [comment]
Interesting... the package tests pass on Chrome but when I import it into my own package and run my own package tests it breaks? Very weird.
Also breaks inside my Flutter app too in release mode but not in debug mode.

**Comment by CDDelta** [comment]
I've fixed the issues above, refer to [here](https://github.com/dart-lang/sdk/issues/42194) for what broke. Is this considered a breaking api change?

**Comment by matehat** [comment]
@terrier989 any chance this 2.5 months old PR gets merged? 

Is this project still alive?

**Comment by CDDelta** [comment]
I'm closing this since it's no longer relevant with the latest release of this package.

**Pull request closed without merging**
